with open("/root/sakana/generator/pipeline.py", "r") as f:
    content = f.read()

# Replace the SEO import/initialization
old_import = "from generator.seo_generator import SEOGenerator"
new_import = "from generator.seo_generator import SEOGenerator\nfrom generator.confession_seo import ConfessionSEOGenerator"
if old_import in content and "ConfessionSEOGenerator" not in content:
    content = content.replace(old_import, new_import)

# Replace SEO initialization in __init__
old_seo_init = "        self.seo = SEOGenerator()"
new_seo_init = "        self.seo = ConfessionSEOGenerator() if self.is_confession else SEOGenerator()"
if old_seo_init not in content:
    # Maybe already patched or different format
    pass
else:
    content = content.replace(old_seo_init, new_seo_init)

# Fix the SEO generation call to ensure confession gets confession metadata
old_seo_gen = '''            # Confession channel: separate SEO metadata from Mia
            if self.is_confession:
                confession_title = plan.get("title", "Confession Story")[:100]
                youtube["title"] = confession_title
                # Strip any Mia/vlog terms, build confession description
                old_desc = youtube.get("description", "")
                if "Mia" in old_desc or "vlog" in old_desc.lower():
                    old_desc = "A real confession story.\\\\n\\\\n" + plan.get("script", "")[:400]
                youtube["description"] = old_desc[:5000]
                confession_tags = ["confession", "reddit story", "real story", "relationship", "drama", "storytime", "cheating", "secrets", "betrayal"]
                existing = [t for t in youtube.get("tags", []) if t.lower() not in ["mia", "daily vlog", "vlogger", "influencer"]]
                youtube["tags"] = list(dict.fromkeys(confession_tags + existing))[:15]
                logger.info("Confession SEO generated: title='%s' tags=%s", confession_title, youtube["tags"])'''
new_seo_gen = '''            # Confession SEO is already generated by ConfessionSEOGenerator
            # Mia SEO is already generated by SEOGenerator
            # Both are channel-separate by design'''
content = content.replace(old_seo_gen, new_seo_gen)

with open("/root/sakana/generator/pipeline.py", "w") as f:
    f.write(content)

print("Patched pipeline.py for separate confession SEO")
