server {
    listen 6464;
    server_name _;
    root /root/sakana/output;
    autoindex off;

    location ~* \.mp4$ {
        add_header Content-Type video/mp4;
        add_header Cache-Control "public, max-age=86400";
    }
}
